{
 "title": "System Maintenance",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Current metric writes per second",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"internal_metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_api_requests_total\" and r[\"method\"] == \"POST\" and r[\"path\"] == \"/api/v2/write\" and r[\"status\"] == \"2XX\")\n  |> derivative(unit: 1s)\n  |> last()\n  ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active Sensors",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"iot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor_status\")\n  |> group(columns: [\"sensor_group\"])\n  |> top(n:1, columns: [\"_time\"])\n  |> unique(column: \"sensor_group\")\n  |> keep(columns: [\"sensor_group\"])\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Metric writes per second",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"internal_metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_api_requests_total\")\n  |> filter(fn: (r) => r[\"method\"] == \"POST\")\n  |> filter(fn: (r) => r[\"path\"] == \"/api/v2/write\")\n  |> filter(fn: (r) => r[\"status\"] == \"2XX\")\n  |> keep(columns: [\"path\", \"_time\", \"_value\"])\n  |> derivative(unit: 1s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active Sensors",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"experimental\"\n\nsensorConfigs = from(bucket: \"iot\")\n  |> range(start: -365d, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor_config\")\n  |> pivot(\n    rowKey:[\"_time\"],\n    columnKey: [\"_field\"],\n    valueColumn: \"_value\"\n  )\n  |> group(columns: [\"sensor_group\"])\n  |> top(n:1, columns: [\"_time\"])\n  |> map(fn: (r) => ({r with expected_data_push: experimental.subDuration(d: duration(v: r.push_interval * 1000000), from: v.timeRangeStop)}))\n  |> drop(columns: [\"_time\", \"_start\", \"_stop\", \"_measurement\"])\n\nlatestPushes = from(bucket: \"iot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor_status\")\n  |> group(columns: [\"sensor_group\"])\n  |> top(n:1, columns: [\"_time\"])\n  |> keep(columns: [\"_time\", \"sensor_group\"])\n  |> rename(columns: {_time: \"last_data_push\"})\n\n\njoin(tables: {d1: sensorConfigs, d2: latestPushes}, on: [\"sensor_group\"], method: \"inner\")\n  |>  map(fn: (r) => ({r with data_lateness: float(v: int(v: experimental.subDuration(d: duration(v: int(v:r.last_data_push)), from: v.timeRangeStop))) / float(v: r.push_interval) / float(v: 1000000)}))\n  |>  map(fn: (r) => ({r with influx_host: r.influx_host + \":\" + r.influx_port}))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}